### PR TITLE
Documentation and error handling for 'tree.order' option

### PR DESCRIPTION
**Pull request by befriendabacterium**
-Added @param with documentation
-Added error handler - if user specifies order of incorrect length, stops function and throws error

### CODE REVIEW

**Comment by befriendabacterium** [comment]
Oh great it's failing everything now :sweat_smile: even worse than last time. Eyeballing the error messages it seems to be having trouble installing orchaRd :thinking:

**Comment by daniel1noble** [comment]
Ha, happens. If you use `devtools::check()` and `devtools::tests()` you should be able to narraow the issues down

**Comment by befriendabacterium** [comment]
Alright with help of a friend @padpadpadpad think have figured out the error and implemented some other corrections to actually get it working...famous last words 🤞

**Comment by befriendabacterium** [comment]
fek

**Comment by padpadpadpad** [comment]
You need to re-run devtools::document() to make sure the help page has your new parameter in.

**Comment by befriendabacterium** [comment]
seems to be running ok now just codecov couldn't check some lines I added but I think OK to merge with one last glance from you?

**Comment by daniel1noble** [comment]
@befriendabacterium This is looking good on my end so I'll merge. Thanks for adding that, and thanks @padpadpadpad for clarifying to Matt on what to do.

**Pull request merged**
